# this is an example file, consult: https://toml.io/en/ and src/rules.rs for
# documentation
[disabled] 
# by default, sqleibniz specific errors are disabled:
rules = [ "NoContent", "NoStatements", "Unimplemented" ]
