use crate::lev;

#[derive(Debug, PartialEq, Clone, Eq, PartialOrd, serde::Serialize, Copy)]
#[allow(non_camel_case_types)]
#[allow(clippy::upper_case_acronyms)]
pub enum Keyword {
    ABORT,
    ACTION,
    ADD,
    AFTER,
    ALL,
    ALTER,
    ALWAYS,
    ANALYZE,
    AND,
    AS,
    ASC,
    ATTACH,
    AUTOINCREMENT,
    BEFORE,
    BEGIN,
    BETWEEN,
    BY,
    CASCADE,
    CASE,
    CAST,
    CHECK,
    COLLATE,
    COLUMN,
    COMMIT,
    CONFLICT,
    CONSTRAINT,
    CREATE,
    CROSS,
    CURRENT,
    CURRENT_DATE,
    CURRENT_TIME,
    CURRENT_TIMESTAMP,
    DATABASE,
    DEFAULT,
    DEFERRABLE,
    DEFERRED,
    DELETE,
    DESC,
    DETACH,
    DISTINCT,
    DO,
    DROP,
    EACH,
    ELSE,
    END,
    ESCAPE,
    EXCEPT,
    EXCLUDE,
    EXCLUSIVE,
    EXISTS,
    EXPLAIN,
    FAIL,
    FILTER,
    FIRST,
    FOLLOWING,
    FOR,
    FOREIGN,
    FROM,
    FULL,
    GENERATED,
    GLOB,
    GROUP,
    GROUPS,
    HAVING,
    IF,
    IGNORE,
    IMMEDIATE,
    IN,
    INDEX,
    INDEXED,
    INITIALLY,
    INNER,
    INSERT,
    INSTEAD,
    INTERSECT,
    INTO,
    IS,
    ISNULL,
    JOIN,
    KEY,
    LAST,
    LEFT,
    LIKE,
    LIMIT,
    MATCH,
    MATERIALIZED,
    NATURAL,
    NO,
    NOT,
    NOTHING,
    NOTNULL,
    NULL,
    NULLS,
    OF,
    OFFSET,
    ON,
    OR,
    ORDER,
    OTHERS,
    OUTER,
    OVER,
    PARTITION,
    PLAN,
    PRAGMA,
    PRECEDING,
    PRIMARY,
    QUERY,
    RAISE,
    RANGE,
    RECURSIVE,
    REFERENCES,
    REGEXP,
    REINDEX,
    RELEASE,
    RENAME,
    REPLACE,
    RESTRICT,
    RETURNING,
    RIGHT,
    ROLLBACK,
    ROW,
    ROWS,
    SAVEPOINT,
    SELECT,
    SET,
    STORED,
    TABLE,
    TEMP,
    TEMPORARY,
    THEN,
    TIES,
    TO,
    TRANSACTION,
    TRIGGER,
    UNBOUNDED,
    UNION,
    UNIQUE,
    UPDATE,
    USING,
    VACUUM,
    VALUES,
    VIEW,
    VIRTUAL,
    WHEN,
    WHERE,
    WINDOW,
    WITH,
    WITHOUT,

    // only necessary, since sqlite does not treat these match types as keywords, so we have to
    // define them by ourselfs
    PARTIAL,
    SIMPLE,
}

static KEYWORDS: &[&str] = &[
    "ABORT",
    "ACTION",
    "ADD",
    "AFTER",
    "ALL",
    "ALTER",
    "ALWAYS",
    "ANALYZE",
    "AND",
    "AS",
    "ASC",
    "ATTACH",
    "AUTOINCREMENT",
    "BEFORE",
    "BEGIN",
    "BETWEEN",
    "BY",
    "CASCADE",
    "CASE",
    "CAST",
    "CHECK",
    "COLLATE",
    "COLUMN",
    "COMMIT",
    "CONFLICT",
    "CONSTRAINT",
    "CREATE",
    "CROSS",
    "CURRENT",
    "CURRENT_DATE",
    "CURRENT_TIME",
    "CURRENT_TIMESTAMP",
    "DATABASE",
    "DEFAULT",
    "DEFERRABLE",
    "DEFERRED",
    "DELETE",
    "DESC",
    "DETACH",
    "DISTINCT",
    "DO",
    "DROP",
    "EACH",
    "ELSE",
    "END",
    "ESCAPE",
    "EXCEPT",
    "EXCLUDE",
    "EXCLUSIVE",
    "EXISTS",
    "EXPLAIN",
    "FAIL",
    "FILTER",
    "FIRST",
    "FOLLOWING",
    "FOR",
    "FOREIGN",
    "FROM",
    "FULL",
    "GENERATED",
    "GLOB",
    "GROUP",
    "GROUPS",
    "HAVING",
    "IF",
    "IGNORE",
    "IMMEDIATE",
    "IN",
    "INDEX",
    "INDEXED",
    "INITIALLY",
    "INNER",
    "INSERT",
    "INSTEAD",
    "INTERSECT",
    "INTO",
    "IS",
    "ISNULL",
    "JOIN",
    "KEY",
    "LAST",
    "LEFT",
    "LIKE",
    "LIMIT",
    "MATCH",
    "MATERIALIZED",
    "NATURAL",
    "NO",
    "NOT",
    "NOTHING",
    "NOTNULL",
    "NULL",
    "NULLS",
    "OF",
    "OFFSET",
    "ON",
    "OR",
    "ORDER",
    "OTHERS",
    "OUTER",
    "OVER",
    "PARTITION",
    "PLAN",
    "PRAGMA",
    "PRECEDING",
    "PRIMARY",
    "QUERY",
    "RAISE",
    "RANGE",
    "RECURSIVE",
    "REFERENCES",
    "REGEXP",
    "REINDEX",
    "RELEASE",
    "RENAME",
    "REPLACE",
    "RESTRICT",
    "RETURNING",
    "RIGHT",
    "ROLLBACK",
    "ROW",
    "ROWS",
    "SAVEPOINT",
    "SELECT",
    "SET",
    "STORED",
    "TABLE",
    "TEMP",
    "TEMPORARY",
    "THEN",
    "TIES",
    "TO",
    "TRANSACTION",
    "TRIGGER",
    "UNBOUNDED",
    "UNION",
    "UNIQUE",
    "UPDATE",
    "USING",
    "VACUUM",
    "VALUES",
    "VIEW",
    "VIRTUAL",
    "WHEN",
    "WHERE",
    "WINDOW",
    "WITH",
    "WITHOUT",
];

impl Keyword {
    /// suggestions returns three suggestions based on their smallest Levenshtein_distance computed via lev::distance
    pub fn suggestions(s: &str) -> Vec<&str> {
        let input = s.to_uppercase();
        let bytes = input.as_bytes();
        let mut best: Vec<(&str, usize)> = Vec::with_capacity(3);
        for keyword in KEYWORDS.iter() {
            let dist = lev::distance(bytes, keyword.as_bytes());

            if best.len() < 3 {
                best.push((keyword, dist));
                best.sort_unstable_by_key(|k| k.1);
            } else if dist < best[2].1 {
                best[2] = (keyword, dist);
                best.sort_unstable_by_key(|k| k.1);
            }
        }

        best.into_iter().map(|(k, _)| k).collect()
    }

    pub fn from_str(s: &str) -> Option<Keyword> {
        Some(match s.to_uppercase().as_str() {
            "ABORT" => Keyword::ABORT,
            "ACTION" => Keyword::ACTION,
            "ADD" => Keyword::ADD,
            "AFTER" => Keyword::AFTER,
            "ALL" => Keyword::ALL,
            "ALTER" => Keyword::ALTER,
            "ALWAYS" => Keyword::ALWAYS,
            "ANALYZE" => Keyword::ANALYZE,
            "AND" => Keyword::AND,
            "AS" => Keyword::AS,
            "ASC" => Keyword::ASC,
            "ATTACH" => Keyword::ATTACH,
            "AUTOINCREMENT" => Keyword::AUTOINCREMENT,
            "BEFORE" => Keyword::BEFORE,
            "BEGIN" => Keyword::BEGIN,
            "BETWEEN" => Keyword::BETWEEN,
            "BY" => Keyword::BY,
            "CASCADE" => Keyword::CASCADE,
            "CASE" => Keyword::CASE,
            "CAST" => Keyword::CAST,
            "CHECK" => Keyword::CHECK,
            "COLLATE" => Keyword::COLLATE,
            "COLUMN" => Keyword::COLUMN,
            "COMMIT" => Keyword::COMMIT,
            "CONFLICT" => Keyword::CONFLICT,
            "CONSTRAINT" => Keyword::CONSTRAINT,
            "CREATE" => Keyword::CREATE,
            "CROSS" => Keyword::CROSS,
            "CURRENT" => Keyword::CURRENT,
            "CURRENT_DATE" => Keyword::CURRENT_DATE,
            "CURRENT_TIME" => Keyword::CURRENT_TIME,
            "CURRENT_TIMESTAMP" => Keyword::CURRENT_TIMESTAMP,
            "DATABASE" => Keyword::DATABASE,
            "DEFAULT" => Keyword::DEFAULT,
            "DEFERRABLE" => Keyword::DEFERRABLE,
            "DEFERRED" => Keyword::DEFERRED,
            "DELETE" => Keyword::DELETE,
            "DESC" => Keyword::DESC,
            "DETACH" => Keyword::DETACH,
            "DISTINCT" => Keyword::DISTINCT,
            "DO" => Keyword::DO,
            "DROP" => Keyword::DROP,
            "EACH" => Keyword::EACH,
            "ELSE" => Keyword::ELSE,
            "END" => Keyword::END,
            "ESCAPE" => Keyword::ESCAPE,
            "EXCEPT" => Keyword::EXCEPT,
            "EXCLUDE" => Keyword::EXCLUDE,
            "EXCLUSIVE" => Keyword::EXCLUSIVE,
            "EXISTS" => Keyword::EXISTS,
            "EXPLAIN" => Keyword::EXPLAIN,
            "FAIL" => Keyword::FAIL,
            "FILTER" => Keyword::FILTER,
            "FIRST" => Keyword::FIRST,
            "FOLLOWING" => Keyword::FOLLOWING,
            "FOR" => Keyword::FOR,
            "FOREIGN" => Keyword::FOREIGN,
            "FROM" => Keyword::FROM,
            "FULL" => Keyword::FULL,
            "GENERATED" => Keyword::GENERATED,
            "GLOB" => Keyword::GLOB,
            "GROUP" => Keyword::GROUP,
            "GROUPS" => Keyword::GROUPS,
            "HAVING" => Keyword::HAVING,
            "IF" => Keyword::IF,
            "IGNORE" => Keyword::IGNORE,
            "IMMEDIATE" => Keyword::IMMEDIATE,
            "IN" => Keyword::IN,
            "INDEX" => Keyword::INDEX,
            "INDEXED" => Keyword::INDEXED,
            "INITIALLY" => Keyword::INITIALLY,
            "INNER" => Keyword::INNER,
            "INSERT" => Keyword::INSERT,
            "INSTEAD" => Keyword::INSTEAD,
            "INTERSECT" => Keyword::INTERSECT,
            "INTO" => Keyword::INTO,
            "IS" => Keyword::IS,
            "ISNULL" => Keyword::ISNULL,
            "JOIN" => Keyword::JOIN,
            "KEY" => Keyword::KEY,
            "LAST" => Keyword::LAST,
            "LEFT" => Keyword::LEFT,
            "LIKE" => Keyword::LIKE,
            "LIMIT" => Keyword::LIMIT,
            "MATCH" => Keyword::MATCH,
            "MATERIALIZED" => Keyword::MATERIALIZED,
            "NATURAL" => Keyword::NATURAL,
            "NO" => Keyword::NO,
            "NOT" => Keyword::NOT,
            "NOTHING" => Keyword::NOTHING,
            "NOTNULL" => Keyword::NOTNULL,
            "NULL" => Keyword::NULL,
            "NULLS" => Keyword::NULLS,
            "OF" => Keyword::OF,
            "OFFSET" => Keyword::OFFSET,
            "ON" => Keyword::ON,
            "OR" => Keyword::OR,
            "ORDER" => Keyword::ORDER,
            "OTHERS" => Keyword::OTHERS,
            "OUTER" => Keyword::OUTER,
            "OVER" => Keyword::OVER,
            "PARTITION" => Keyword::PARTITION,
            "PLAN" => Keyword::PLAN,
            "PRAGMA" => Keyword::PRAGMA,
            "PRECEDING" => Keyword::PRECEDING,
            "PRIMARY" => Keyword::PRIMARY,
            "QUERY" => Keyword::QUERY,
            "RAISE" => Keyword::RAISE,
            "RANGE" => Keyword::RANGE,
            "RECURSIVE" => Keyword::RECURSIVE,
            "REFERENCES" => Keyword::REFERENCES,
            "REGEXP" => Keyword::REGEXP,
            "REINDEX" => Keyword::REINDEX,
            "RELEASE" => Keyword::RELEASE,
            "RENAME" => Keyword::RENAME,
            "REPLACE" => Keyword::REPLACE,
            "RESTRICT" => Keyword::RESTRICT,
            "RETURNING" => Keyword::RETURNING,
            "RIGHT" => Keyword::RIGHT,
            "ROLLBACK" => Keyword::ROLLBACK,
            "ROW" => Keyword::ROW,
            "ROWS" => Keyword::ROWS,
            "SAVEPOINT" => Keyword::SAVEPOINT,
            "SELECT" => Keyword::SELECT,
            "SET" => Keyword::SET,
            "STORED" => Keyword::STORED,
            "TABLE" => Keyword::TABLE,
            "TEMP" => Keyword::TEMP,
            "TEMPORARY" => Keyword::TEMPORARY,
            "THEN" => Keyword::THEN,
            "TIES" => Keyword::TIES,
            "TO" => Keyword::TO,
            "TRANSACTION" => Keyword::TRANSACTION,
            "TRIGGER" => Keyword::TRIGGER,
            "UNBOUNDED" => Keyword::UNBOUNDED,
            "UNION" => Keyword::UNION,
            "UNIQUE" => Keyword::UNIQUE,
            "UPDATE" => Keyword::UPDATE,
            "USING" => Keyword::USING,
            "VACUUM" => Keyword::VACUUM,
            "VALUES" => Keyword::VALUES,
            "VIEW" => Keyword::VIEW,
            "VIRTUAL" => Keyword::VIRTUAL,
            "WHEN" => Keyword::WHEN,
            "WHERE" => Keyword::WHERE,
            "WINDOW" => Keyword::WINDOW,
            "WITH" => Keyword::WITH,
            "WITHOUT" => Keyword::WITHOUT,
            "PARTIAL" => Keyword::PARTIAL,
            "SIMPLE" => Keyword::SIMPLE,
            _ => return None,
        })
    }
}

impl From<Keyword> for &str {
    fn from(value: Keyword) -> Self {
        match value {
            Keyword::ABORT => "ABORT",
            Keyword::ACTION => "ACTION",
            Keyword::ADD => "ADD",
            Keyword::AFTER => "AFTER",
            Keyword::ALL => "ALL",
            Keyword::ALTER => "ALTER",
            Keyword::ALWAYS => "ALWAYS",
            Keyword::ANALYZE => "ANALYZE",
            Keyword::AND => "AND",
            Keyword::AS => "AS",
            Keyword::ASC => "ASC",
            Keyword::ATTACH => "ATTACH",
            Keyword::AUTOINCREMENT => "AUTOINCREMENT",
            Keyword::BEFORE => "BEFORE",
            Keyword::BEGIN => "BEGIN",
            Keyword::BETWEEN => "BETWEEN",
            Keyword::BY => "BY",
            Keyword::CASCADE => "CASCADE",
            Keyword::CASE => "CASE",
            Keyword::CAST => "CAST",
            Keyword::CHECK => "CHECK",
            Keyword::COLLATE => "COLLATE",
            Keyword::COLUMN => "COLUMN",
            Keyword::COMMIT => "COMMIT",
            Keyword::CONFLICT => "CONFLICT",
            Keyword::CONSTRAINT => "CONSTRAINT",
            Keyword::CREATE => "CREATE",
            Keyword::CROSS => "CROSS",
            Keyword::CURRENT => "CURRENT",
            Keyword::CURRENT_DATE => "CURRENT_DATE",
            Keyword::CURRENT_TIME => "CURRENT_TIME",
            Keyword::CURRENT_TIMESTAMP => "CURRENT_TIMESTAMP",
            Keyword::DATABASE => "DATABASE",
            Keyword::DEFAULT => "DEFAULT",
            Keyword::DEFERRABLE => "DEFERRABLE",
            Keyword::DEFERRED => "DEFERRED",
            Keyword::DELETE => "DELETE",
            Keyword::DESC => "DESC",
            Keyword::DETACH => "DETACH",
            Keyword::DISTINCT => "DISTINCT",
            Keyword::DO => "DO",
            Keyword::DROP => "DROP",
            Keyword::EACH => "EACH",
            Keyword::ELSE => "ELSE",
            Keyword::END => "END",
            Keyword::ESCAPE => "ESCAPE",
            Keyword::EXCEPT => "EXCEPT",
            Keyword::EXCLUDE => "EXCLUDE",
            Keyword::EXCLUSIVE => "EXCLUSIVE",
            Keyword::EXISTS => "EXISTS",
            Keyword::EXPLAIN => "EXPLAIN",
            Keyword::FAIL => "FAIL",
            Keyword::FILTER => "FILTER",
            Keyword::FIRST => "FIRST",
            Keyword::FOLLOWING => "FOLLOWING",
            Keyword::FOR => "FOR",
            Keyword::FOREIGN => "FOREIGN",
            Keyword::FROM => "FROM",
            Keyword::FULL => "FULL",
            Keyword::GENERATED => "GENERATED",
            Keyword::GLOB => "GLOB",
            Keyword::GROUP => "GROUP",
            Keyword::GROUPS => "GROUPS",
            Keyword::HAVING => "HAVING",
            Keyword::IF => "IF",
            Keyword::IGNORE => "IGNORE",
            Keyword::IMMEDIATE => "IMMEDIATE",
            Keyword::IN => "IN",
            Keyword::INDEX => "INDEX",
            Keyword::INDEXED => "INDEXED",
            Keyword::INITIALLY => "INITIALLY",
            Keyword::INNER => "INNER",
            Keyword::INSERT => "INSERT",
            Keyword::INSTEAD => "INSTEAD",
            Keyword::INTERSECT => "INTERSECT",
            Keyword::INTO => "INTO",
            Keyword::IS => "IS",
            Keyword::ISNULL => "ISNULL",
            Keyword::JOIN => "JOIN",
            Keyword::KEY => "KEY",
            Keyword::LAST => "LAST",
            Keyword::LEFT => "LEFT",
            Keyword::LIKE => "LIKE",
            Keyword::LIMIT => "LIMIT",
            Keyword::MATCH => "MATCH",
            Keyword::MATERIALIZED => "MATERIALIZED",
            Keyword::NATURAL => "NATURAL",
            Keyword::NO => "NO",
            Keyword::NOT => "NOT",
            Keyword::NOTHING => "NOTHING",
            Keyword::NOTNULL => "NOTNULL",
            Keyword::NULL => "NULL",
            Keyword::NULLS => "NULLS",
            Keyword::OF => "OF",
            Keyword::OFFSET => "OFFSET",
            Keyword::ON => "ON",
            Keyword::OR => "OR",
            Keyword::ORDER => "ORDER",
            Keyword::OTHERS => "OTHERS",
            Keyword::OUTER => "OUTER",
            Keyword::OVER => "OVER",
            Keyword::PARTITION => "PARTITION",
            Keyword::PLAN => "PLAN",
            Keyword::PRAGMA => "PRAGMA",
            Keyword::PRECEDING => "PRECEDING",
            Keyword::PRIMARY => "PRIMARY",
            Keyword::QUERY => "QUERY",
            Keyword::RAISE => "RAISE",
            Keyword::RANGE => "RANGE",
            Keyword::RECURSIVE => "RECURSIVE",
            Keyword::REFERENCES => "REFERENCES",
            Keyword::REGEXP => "REGEXP",
            Keyword::REINDEX => "REINDEX",
            Keyword::RELEASE => "RELEASE",
            Keyword::RENAME => "RENAME",
            Keyword::REPLACE => "REPLACE",
            Keyword::RESTRICT => "RESTRICT",
            Keyword::RETURNING => "RETURNING",
            Keyword::RIGHT => "RIGHT",
            Keyword::ROLLBACK => "ROLLBACK",
            Keyword::ROW => "ROW",
            Keyword::ROWS => "ROWS",
            Keyword::SAVEPOINT => "SAVEPOINT",
            Keyword::SELECT => "SELECT",
            Keyword::SET => "SET",
            Keyword::STORED => "STORED",
            Keyword::TABLE => "TABLE",
            Keyword::TEMP => "TEMP",
            Keyword::TEMPORARY => "TEMPORARY",
            Keyword::THEN => "THEN",
            Keyword::TIES => "TIES",
            Keyword::TO => "TO",
            Keyword::TRANSACTION => "TRANSACTION",
            Keyword::TRIGGER => "TRIGGER",
            Keyword::UNBOUNDED => "UNBOUNDED",
            Keyword::UNION => "UNION",
            Keyword::UNIQUE => "UNIQUE",
            Keyword::UPDATE => "UPDATE",
            Keyword::USING => "USING",
            Keyword::VACUUM => "VACUUM",
            Keyword::VALUES => "VALUES",
            Keyword::VIEW => "VIEW",
            Keyword::VIRTUAL => "VIRTUAL",
            Keyword::WHEN => "WHEN",
            Keyword::WHERE => "WHERE",
            Keyword::WINDOW => "WINDOW",
            Keyword::WITH => "WITH",
            Keyword::WITHOUT => "WITHOUT",
            _ => unreachable!(),
        }
    }
}
